server:
  port: 8000
  
zuul:
  routes:
    exchange-rate-provider:
      path: /exchangeRate/**
      strip-prefix: false
      url: http://localhost:7070
    eureka:
      path: /
      strip-prefix: false
      url: http://localhost:9090